### ISSUE TITLE
Can we get support for .tgz files?

### ISSUE THREAD

**Issue by owencraston** [Light-Untar/Light-Swift-Untar#5]
I am not sure how this would be achieved but if we could support `.tgz` files that would be amazing.

**Comment by owencraston** [comment]
currently when I try it throws an error saying the file is corrupted.

**Comment by UInt2048** [comment]
That’s correct. The README explicitly states that this code does not support gzip compression.

**Comment by owencraston** [comment]
It was a request 😢

**Comment by UInt2048** [comment]
Currently not planned to support
